export const bookingT: Record<string, Record<string, string>> = {
  en: { title:"Book Your Free Consultation", subtitle:"Choose a date and time slot", date:"Select a Date", time:"Select a Time Slot", name:"Your Full Name", email:"Your Email", phone:"Your Phone Number", confirm:"Confirm Booking", success:"✓ Booking Request Sent!", successMsg:"A confirmation email has been sent to info@aureus-ia.com. We will get back to you within 24 hours.", close:"Close", back:"← Back", next:"Next →", weekdays:"Mon,Tue,Wed,Thu,Fri,Sat,Sun", months:"January,February,March,April,May,June,July,August,September,October,November,December", duration:"30 min — Free Consultation", closed:"Closed (Weekend)", step1:"1. Date", step2:"2. Time", step3:"3. Details" },
  fr: { title:"Réservez Votre Consultation Gratuite", subtitle:"Choisissez une date et un créneau", date:"Sélectionnez une Date", time:"Sélectionnez un Créneau", name:"Votre Nom Complet", email:"Votre Email", phone:"Votre Numéro de Téléphone", confirm:"Confirmer la Réservation", success:"✓ Demande Envoyée !", successMsg:"Un email de confirmation a été envoyé à info@aureus-ia.com. Nous vous recontacterons sous 24 heures.", close:"Fermer", back:"← Retour", next:"Suivant →", weekdays:"Lun,Mar,Mer,Jeu,Ven,Sam,Dim", months:"Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre", duration:"30 min — Consultation Gratuite", closed:"Fermé (Week-end)", step1:"1. Date", step2:"2. Heure", step3:"3. Infos" },
  nl: { title:"Boek Uw Gratis Consultatie", subtitle:"Kies een datum en tijdslot", date:"Selecteer een Datum", time:"Selecteer een Tijdslot", name:"Uw Volledige Naam", email:"Uw Email", phone:"Uw Telefoonnummer", confirm:"Bevestig Boeking", success:"✓ Aanvraag Verzonden!", successMsg:"Een bevestigingsmail is verzonden naar info@aureus-ia.com.", close:"Sluiten", back:"← Terug", next:"Volgende →", weekdays:"Ma,Di,Wo,Do,Vr,Za,Zo", months:"Januari,Februari,Maart,April,Mei,Juni,Juli,Augustus,September,Oktober,November,December", duration:"30 min — Gratis Consultatie", closed:"Gesloten (Weekend)", step1:"1. Datum", step2:"2. Tijd", step3:"3. Gegevens" },
  de: { title:"Buchen Sie Ihre Kostenlose Beratung", subtitle:"Wählen Sie Datum und Zeitfenster", date:"Datum Wählen", time:"Zeitfenster Wählen", name:"Ihr Vollständiger Name", email:"Ihre Email", phone:"Ihre Telefonnummer", confirm:"Buchung Bestätigen", success:"✓ Anfrage Gesendet!", successMsg:"Eine Bestätigungsmail wurde an info@aureus-ia.com gesendet.", close:"Schließen", back:"← Zurück", next:"Weiter →", weekdays:"Mo,Di,Mi,Do,Fr,Sa,So", months:"Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember", duration:"30 min — Kostenlose Beratung", closed:"Geschlossen (Wochenende)", step1:"1. Datum", step2:"2. Zeit", step3:"3. Details" },
  es: { title:"Reserve Su Consulta Gratuita", subtitle:"Elija fecha y horario", date:"Seleccione Fecha", time:"Seleccione Horario", name:"Su Nombre Completo", email:"Su Email", phone:"Su Teléfono", confirm:"Confirmar Reserva", success:"✓ Solicitud Enviada!", successMsg:"Un email de confirmación fue enviado a info@aureus-ia.com.", close:"Cerrar", back:"← Atrás", next:"Siguiente →", weekdays:"Lun,Mar,Mié,Jue,Vie,Sáb,Dom", months:"Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre", duration:"30 min — Consulta Gratuita", closed:"Cerrado (Fin de semana)", step1:"1. Fecha", step2:"2. Hora", step3:"3. Datos" },
  pt: { title:"Reserve Sua Consulta Gratuita", subtitle:"Escolha data e horário", date:"Selecione Data", time:"Selecione Horário", name:"Seu Nome Completo", email:"Seu Email", phone:"Seu Telefone", confirm:"Confirmar Reserva", success:"✓ Pedido Enviado!", successMsg:"Um email de confirmação foi enviado para info@aureus-ia.com.", close:"Fechar", back:"← Voltar", next:"Seguinte →", weekdays:"Seg,Ter,Qua,Qui,Sex,Sáb,Dom", months:"Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro", duration:"30 min — Consulta Gratuita", closed:"Fechado (Fim de semana)", step1:"1. Data", step2:"2. Hora", step3:"3. Dados" },
  ru: { title:"Забронируйте Бесплатную Консультацию", subtitle:"Выберите дату и время", date:"Выберите Дату", time:"Выберите Время", name:"Ваше Полное Имя", email:"Ваш Email", phone:"Ваш Телефон", confirm:"Подтвердить", success:"✓ Запрос Отправлен!", successMsg:"Подтверждение отправлено на info@aureus-ia.com.", close:"Закрыть", back:"← Назад", next:"Далее →", weekdays:"Пн,Вт,Ср,Чт,Пт,Сб,Вс", months:"Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь", duration:"30 мин — Бесплатная Консультация", closed:"Закрыто (Выходные)", step1:"1. Дата", step2:"2. Время", step3:"3. Данные" },
  ar: { title:"احجز استشارتك المجانية", subtitle:"اختر التاريخ والوقت", date:"اختر التاريخ", time:"اختر الوقت", name:"اسمك الكامل", email:"بريدك الإلكتروني", phone:"رقم هاتفك", confirm:"تأكيد الحجز", success:"✓ تم الإرسال!", successMsg:"تم إرسال تأكيد إلى info@aureus-ia.com.", close:"إغلاق", back:"رجوع ←", next:"→ التالي", weekdays:"إث,ثل,أر,خم,جم,سب,أح", months:"يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر", duration:"30 دقيقة — استشارة مجانية", closed:"مغلق (عطلة)", step1:"1. التاريخ", step2:"2. الوقت", step3:"3. البيانات" },
};

export const timeSlots = [
  "09:00","09:30","10:00","10:30","11:00","11:30",
  "12:00","12:30","13:00","13:30","14:00","14:30",
  "15:00","15:30","16:00"
];
